### PR TITLE
[Fixes #33] Patching fails for non 'object' value type dictionaries

### LINKED ISSUE #33: Patching fails for non 'object' value type dictionaries
Given a model like this:

```csharp
public class DemoModel
{
  public DemoModel()
  {
    this.Numbers = new Dictionary<string, int>();
  }

  public IDictionary<string, int> Numbers { get; private set; }
}
```

When JSON serialized, the object looks like this:

```json
{
  "Numbers": {
    "one":1,
    "two":2
  }
}
```

If I try to create a patch document and apply it, it fails:

```csharp
[Fact]
public void DictionaryTest()
{
  var model = new DemoModel();
  model.Numbers["one"] = 1;
  model.Numbers["two"] = 2;

  var patch = new JsonPatchDocument();
  patch.Operations.Add(new Operation("add", "/Numbers/three", null, 3));
  patch.ApplyTo(model);

  Assert.Equal(3, model.Numbers.Count);
  Assert.Equal(1, model.Numbers["one"]);
  Assert.Equal(2, model.Numbers["two"]);
  Assert.Equal(3, model.Numbers["three"]);
}
```

The test fails on the `patch.ApplyTo(model)` line:

```
at Microsoft.AspNetCore.JsonPatch.Helpers.ObjectTreeAnalysisResult..ctor(Object objectToSearch, String propertyPath, IContractResolver contractResolver)
   at Microsoft.AspNetCore.JsonPatch.Adapters.ObjectAdapter.Add(String path, Object value, Object objectToApplyTo, Operation operationToReport)
   at Microsoft.AspNetCore.JsonPatch.Adapters.ObjectAdapter.Add(Operation operation, Object objectToApplyTo)
   at Microsoft.AspNetCore.JsonPatch.JsonPatchDocument.ApplyTo(Object objectToApplyTo, IObjectAdapter adapter)
   at DemoProject.DictionaryTest() in C:\path\to\Fixture.cs:line 73
Result Message:	Unable to cast object of type 'Newtonsoft.Json.Serialization.JsonDictionaryContract' to type 'Newtonsoft.Json.Serialization.JsonObjectContract'.
```

Is this a known issue? Or is there a workaround?

### PR DESCRIPTION
**Pull request by kichalla**
@rynowak @dougbu 

This is a fairly big change, but I can go through it with you and explain. All the existing tests pass and I have added some new coverage too.

### CODE REVIEW

**Comment by kichalla** [comment]
@dougbu @rynowak The latest commit has changes related to our discussions yesterday. Let me know how it looks. (All the tests pass with these changes, but since this new commit creates new classes, I yet need to write unit tests for them, but would like know if this looks the way you expect)

File: src/Microsoft.AspNetCore.JsonPatch/Adapters/ObjectAdapter.cs [hunk 1]
```diff
@@ -139,226 +136,27 @@ public void Add(Operation operation, object objectToApplyTo)
...
-                else
-                {
-                    // New property - add it.  
-                    treeAnalysisResult.Container.Add(treeAnalysisResult.PropertyPathInParent, value);
-                }
+                var patchObject = ObjectVisitor.Visit(context);
+                patchObject.Add(value);
             }
-            else
+            catch (JsonPatchException exception)
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.JsonPatch/Adapters/ObjectAdapter.cs]: This could also use `catch (...) when (...)` which would be an improvement in clarity as well as provide essential PranavPoints.

File: src/Microsoft.AspNetCore.JsonPatch/Internal/DictionaryObjectVisitor.cs [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+            var _dictionary = (IDictionary)context.TargetObject;
+
+            // Since PathSegment is struct and the dictionary's key is of type 'object', convert it explicitly to
+            // string, otherwise look up will fail.
+            var key = pathSegment.ToString();
+
+            // Example: /USStatesProperty/WA
+            if (pathSegment.IsFinal)
+            {
+                return new PatchDictionaryObject(_dictionary, pathSegment, context.Operation);
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.JsonPatch/Internal/DictionaryObjectVisitor.cs]: This is different than what we talked about

File: src/Microsoft.AspNetCore.JsonPatch/Internal/DictionaryObjectVisitor.cs [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+            }
+            else if (_dictionary.Contains(key))
+            {
+                // Example path: "/Customers/101/Address/Zipcode" and
+                // let's say the current path segment is "101"
+                var newTargetObject = _dictionary[key];
+                context.SetNewTargetObject(newTargetObject);
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.JsonPatch/Internal/DictionaryObjectVisitor.cs]: Put the state on the Visitor, not on a Context.

File: src/Microsoft.AspNetCore.JsonPatch/Internal/ExpandoObjectDictionaryExtensions.cs [hunk 4]
```diff
@@ -1,13 +1,13 @@
-// Copyright (c) .NET Foundation. All rights reserved.
+﻿// Copyright (c) .NET Foundation. All rights reserved.
 // Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
 
 using System;
 using System.Collections.Generic;
 
-namespace Microsoft.AspNetCore.JsonPatch.Helpers
+namespace Microsoft.AspNetCore.JsonPatch.Internal
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.JsonPatch/Internal/ExpandoObjectDictionaryExtensions.cs]: :heart_eyes:

**Comment by kichalla** [comment]
🆙 📅

File: src/Microsoft.AspNetCore.JsonPatch/Internal/ObjectVisitor.cs [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+            if (target == null)
+            {
+                adapter = null;
+                errorMessage = null;
+                return false;
+            }
+
+            adapter = SelectAdapater(target);
+
+            // Traverse till the penultimate segment to get the target object and adapter
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.JsonPatch/Internal/ObjectVisitor.cs]: 22 RyanPoints awarded

File: test/Microsoft.AspNetCore.JsonPatch.Test/ErrorMessageFormats.cs [hunk 6]
```diff
@@ -0,0 +1,31 @@
+﻿
+
+namespace Microsoft.AspNetCore.JsonPatch
+{
+    public static class ErrorMessageFormats
```
Comment (rynowak) [inline test/Microsoft.AspNetCore.JsonPatch.Test/ErrorMessageFormats.cs]: We don't generally do things like this, our general practice is to just put the text in the test.  The **reason** for this is so that you have to double check that the message makes sense in all the cases it is used when making changes. Doing things this way defeats that.

This is one of @Eilon 's rules

File: src/Microsoft.AspNetCore.JsonPatch/Internal/ObjectVisitor.cs (hunk 5 above)
Comment (Eilon) [inline src/Microsoft.AspNetCore.JsonPatch/Internal/ObjectVisitor.cs]: -1 EilonPoint for using "till" instead of "til" (or " 'til ")
