### PR TITLE
[Fixes #48] Regression: List add must support adding items where index is same as count of elements

### LINKED ISSUE #48: Simple add on Lists failing in 1.1.0+
Working on 1.0.0, but failing on 1.1.0 and 1.2.0-preview1-22759

Here I'm attempting to add a new entry on List named Mylist which already has two entries (at indexes zero and one)

`[{"op":"add","path":"/mylist/2","value":{"myname":"foo","age":33}}]`

Response:
JsonPatchException: The index value provided by path segment '2' is out of bounds of the array size.

I'm guessing it's incorrectly looking at the length of the list prior to adding. With a dash at the end instead of the new index, this **will** work:

`[{"op":"add","path":"/mylist/-","value":{"myname":"foo","age":33}}]`

### PR DESCRIPTION
**Pull request by kichalla**
…x is same as count of elements

NOTE: this fix is for 1.1.1 branch

### CODE REVIEW

**Comment by jbagga** [comment]
Any reason why [`ListAdapterTests`](https://github.com/aspnet/JsonPatch/blob/f314d7fb156d95a814868b62f31b3faeba6401d5/test/Microsoft.AspNetCore.JsonPatch.Test/ListAdapterTest.cs) do not have coverage for any other methods except `TryAdd` or `TryReplace`? Are they covered in another set of tests?

File: src/Microsoft.AspNetCore.JsonPatch/Internal/ListAdapter.cs [hunk 1]
```diff
@@ -261,6 +266,14 @@ private bool TryGetPositionInfo(IList list, string segment, out PositionInfo pos
                     errorMessage = null;
                     return true;
                 }
+                // As per JSON Patch spec, for Add operation the index value representing the number of elements is valid,
+                // where as for other operations like Remove, Replace, Move and Copy the target index MUST exist.
+                else if (position == list.Count && operationType == OperationType.Add)
+                {
+                    positionInfo = new PositionInfo(PositionType.EndOfList, -1);
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.JsonPatch/Internal/ListAdapter.cs]: Will this muck anything else up? Since we've now *lost* the fact that the index was provided, and the index was the end of the list, not `-1`

Comment (kichalla) [inline src/Microsoft.AspNetCore.JsonPatch/Internal/ListAdapter.cs]: No this does not cause any issues because we consider value of the index only when when the PositionType is Index.
